spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/WeatherClothes
    username: ${USER}
    password: ${PASSWORD}
  jpa:
    generate-ddl: true

api_host: ${API_HOST}
api_key: ${API_KEY}

mail_to: ${MAIL_TO}
password_mail: ${PASSWORD_MAIL}
mail_from: ${MAIL_FROM}

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health